### ISSUE TITLE
[Feat] 강조색 전역 상태관리

### ISSUE THREAD

**Issue by howooking** [KDT5-FE-M6-team3/toy3#10]
## 💡 기능 설명
- 리액트 context api를 이용하여 강조색 전역 상태관리
- 강조색을 변경하면 웹앱에서 모든 강조색이 변경된다.

## 📝 ToDo
- [x] 강조색 context 생성
- [x] 강조색 context provider wrapping
- [x] 강조색 context hook 생성
- [x] 강조색을 선택할 수 있는 color picker ui 생성
- [x]  강조색 context 값들을 원하는 곳에서 사용
