### ISSUE TITLE
Feat: 검색 기능

### ISSUE THREAD

**Issue by howooking** [KDT5-FE-M6-team3/toy3#4]
# Todo
- [ ] 검색 input창 생성
- 검색어 유효성 검사
  -  [ ] 비어있는 경우 통신x
- [ ] 검색 자동완성
- [ ] 검색 결과 모달 창
