### ISSUE TITLE
[Feat] 메인페이지 달력

### ISSUE THREAD

**Issue by 96uoow** [KDT5-FE-M6-team3/toy3#5]
## 💡 기능설명
-메인페이지에 소비기록(당일 소비횟수, 총금액) 확인이 가능한 달력
-날짜 클릭시 해당일의 소비기록 확인할 수 있는 모달창

## 📝 ToDo
- [ ] 메인 페이지에 달력 추가
- [ ] 날짜별로 소비기록(소비횟수, 총금액) 추가
- [ ] 날짜 클릭시 해당일의 소비기록 보여주는 모달창
