### ISSUE TITLE
[Feat] 월별 소비 금액 차트

### ISSUE THREAD

**Issue by howooking** [KDT5-FE-M6-team3/toy3#8]
## 💡 기능 설명
"/statistics" 페이지에 월별 소비 금액을 막대그래프로 표시

## 📝 ToDo
- [x] chartjs 사용
- [x] 월별 소비금액을 가져오는 통신 구현
- [x] chartjs에서 원하는 데이터 형식으로 가공
- [x] chart에 해당하는 데이터를 표현
